- name: Maintenance on TSE
  hosts: all
  vars:
      Message: Message de test Ansible
  tasks:
  - name: Ping TSE
    win_ping:
    
  - name: send msg
    win_shell: msg.exe /server:172.180.0.100 * "{{ Message }}"
